### ISSUE TITLE
The attribute publisher.itemtype has an invalid value.

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-simple-schema#13]
With Person selected, with this output:
`<div itemprop="publisher" itemscope itemtype="http://schema.org/Person">`

Google reports an error : The attribute publisher.itemtype has an invalid value.

http://stackoverflow.com/questions/40565885/the-attribute-publisher-itemtype-has-an-invalid-value
The error is informing you that the itemtype you provided for the publisher property is invalid. Whilst schema.org does support the type Person for the publisher property of Article, Google does not. Google only supports Organization, not Person, as the type for the publisher property, as mentioned in the Articles Structured Data page on Google Developers.

**Comment by dreamwhisper** [comment]
Noting, this issue occurs with `BlogPosting` and `Article`, not `CreativeWork`.

**Comment by dreamwhisper** [comment]
Note: testing matrix at https://docs.google.com/a/copyblogger.com/spreadsheets/d/13kdNxRdS-N9Nzd9fw987rBsGuBnPpvT5i9Ql03FFooA/edit?usp=sharing

**Comment by dreamwhisper** [comment]
Possible Suggestion: When `Article` or `BlogPosting` are selected, allow only `Organization` to be selected to meet Google's requirements.

**Comment by nathanrice** [comment]
>Whilst schema.org does support the type Person for the publisher property of Article, Google does not. 

Yeah, I actually confronted all these issues during development too, and my conclusion was that we should stick with the decentralized standard, rather than just Google. That may be controversial, and I'm certainly willing to discuss the pros and cons, but to me, schema.org being a "a collaborative, community activity" supported by "Google, Microsoft, Yahoo and Yandex", it made more sense to side with the community rather than a single corporation.
